### ISSUE TITLE
Re: How to create the latest version of GLG2D jar file

### ISSUE THREAD

**Issue by chinnaswamyg** [brandonborkholder/glg2d#30]
Dear Brandon,
                        I am developing a java2D interactive graphics application for a scientific computation program which has many points /vertices, lines, shapes  etc with many mouse listeners.  To improve its performance, I found your GLG2D library is the most suitable option. But the GLG2d.jar, glg2d-0.3-20130517.133836-3.jar downloaded from www.java2s.com ( glg2d-master.zip) doesn't seem as the latest.

I am not familiar with Maven to build a new latest glg2d jar from the latest repository of your source code in github web site.  Please advise how to create the latest glg2d.jar file.

High appreciation and advance thanks.

Chinnaswamy
Singapore

**Comment by ritschwumm** [comment]
it should suffice to
- install maven
- go into the the glg2d directory
- issue a `mvn package` in the shell
- look into the `target/` directory

**Comment by chinnaswamyg** [comment]
So nice of you for your prompt reply. I could create the required jar file as per your suggestion
