### ISSUE TITLE
Deploy uberjar with jogl inside it

### ISSUE THREAD

**Issue by aeris170** [brandonborkholder/glg2d#37]
Since glg2d requires jogl, why not put jogl inside it? Makes easier to integrate into maven by only one dependency instead of 3.

**Comment by brandonborkholder** [comment]
1) the way jogl loads native libraries makes this very difficult. It
depends on jar names.
2) it's more maven-like to declare a dependency in the pom rather than make
an uberjar.

What is your use case that you want it all in one jar?

**Comment by aeris170** [comment]
I tried incorporating glg2d into my 2D game engine and failed. I had to build glg2d, install it to my local repository and fetch it from there. The problem with this approach was, building the project was not enough to start using glg2d. I now have to depend on JOGL, which I have no idea how to, since I've not worked with anything that requires natives with maven.

You are right about both your points though. Can you help me about depending on glg2d-0.5-SNAPSHOT (clone and build from this repo) and JOGL?
